name: "K8s Deploy Action"
description: "Runs helm/kubectl commands using kubeconfig from env"
inputs:
  command:
    description: "The shell command to run"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args: []  # Empty, so the input is passed as INPUT_COMMAND env var